name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-artifact:
    uses: ./.github/workflows/create-distribution-artifact.yml
    with:
      upload-artifact: true
  
  create-release:
    needs: create-artifact
    runs-on: windows-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: actor-framework-distribution
          path: artifact-staging
      
      - name: Create actor-framework-distribution.zip
        shell: pwsh
        run: |
          Compress-Archive -Path artifact-staging\* -DestinationPath actor-framework-distribution.zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: actor-framework-distribution.zip
          generate_release_notes: true